### ISSUE TITLE
Creating branch from commit

### ISSUE THREAD

**Issue by PeqNP** [Pylons/acidfs#4]
This may already be supported, but it's not obvious from the docs. Is there a way to create a branch from the commit rather than committing directly into `master`? The idea is to require approval, using a pull/merge request, before a change can be committed to `master`.

**Comment by stevepiercy** [comment]
@PeqNP sure, it's git. Fork the project. Do work on your fork. Then whenever you want to merge back any of your changes to this project, you can open a pull request that merges your changes into this project's `master` or any other branch.

**Comment by PeqNP** [comment]
I'm not being very clear. Sorry!

I figured it out. The idea was to perform all changes on a branch, rather than on `master` directly -- or whatever the active branch was. This can be achieved by passing the `head` parameter to the AcidFS init.

```
fs = acidfs.AcidFS(repo_path, head="new_branch")
```

This creates the branch and includes all operations on this branch. Now it's a cinch to automate the creation of a pull request.
